Merged PR 3671: CDP-4693/PIN the cryptography library due to Azure error
<!--
#csf:3.3.5h:We use a PR template to remind everyone of our way of working and the Cloud Security Framework.
-->
## Why this PR is needed:

The following error occurs in the function:
```
Result: Failure Exception: ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/_rust.abi3.so). Cannot find module. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound. Current sys.path: ['/tmp/functions\\standby\\wwwroot', '/home/site/wwwroot/.python_packages/lib/site-packages', '/azure-functions-host/workers/python/3.10/LINUX/X64', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10',
```
This change should fix it.

## Related Tickets & Documents

- link to Jira issue to be solved by this PR:
  - https://jira/browse/CDP-4693

## I (creator of this PR):

- [X] ✨ have chosen a clear title for this PR
  - This will greatly help my colleagues understand where changes come from
  - Template for PR name: starting with the related Jira issue and actively describing what this change does, e.g. `CDP-2024/Add PR Template`
- [X] 👷‍♀️ created a small PR covering a single issue, allowing for effective review.
- [X] 🙌 am aware of and followed best practices documented on [the wiki](https://dev.azure.com/NIBC/Data%20Platform/_wiki/wikis/Data-Platform.wiki/1525/Azure-Data-Factory)
- [X] 💫 wrote clear, explicit code and added short comments where needed
- [X] 📗 updated any related documentation and included any relevant screenshots.
- [X] 🔐 am aware of the [cloud security framework](https://dev.azure.com/NIBC/Data%20Platform/_git/cloud-security-framework-evidence) and this PR does not go against the measure we take to be in control of our security